name: KitPvPCore
version: '${project.version}'
main: it.samuconfaa.kitpvpcore.KitPvPCore
depend: [Citizens] [PlaceholderAPI] [Vault]
commands:
  build:
  fix:
  reload:
  stats:
  drop:
  kitnpc:
  shop:
  kitnpclist:

permissions:
  kitpvp.build: command /build
  kitpvp.npc: add or remove npc
  kitpvp.reload: for /kitreload (reload config file)
