name: KitPvPCore
version: '${project.version}'
main: it.samuconfaa.kitpvpcore.KitPvPCore
depend: [Citizens] [PlaceholderAPI] [Vault]
commands:
  build:
  fix:
  reload:
  stats:
  drop:
  kitnpc:
  shop:
  kitnpclist:
